# Generated by Django 4.1.5 on 2023-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPersona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adulto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=40)),
                ('trabajo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adulto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=40)),
                ('trabajo', models.CharField(max_length=50)),
            ],
        ),
    ]
